spring:
  application:
    name: queue-a-redis-sorted-set
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

logging:
  level:
    root: INFO
    com.dongwoo.queuea: INFO
